### ISSUE TITLE
Error in reading ASAs

### ISSUE THREAD

**Issue by Mariichen** [HashingSlash/AlgoCSV#1]
getting ASA ID:  163650
getting ASA ID:  300208676
getting ASA ID:  188080731
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-6388d2d2adb6> in <module>()
    303     else:
    304         print('getting ASA ID: ', str(asaID))
--> 305         asaDB.update({asaID: getAsa(str(asaID))})
    306 
    307 #----------#        Row Building

<ipython-input-1-6388d2d2adb6> in getAsa(asaID)
    282     asaDetails = asaJSON['asset']
    283     asaParams = asaDetails['params']
--> 284     if asaParams['unit-name'] == 'TM1POOL':
    285         asaPoolTick = asaParams['name']
    286         asaPoolTickCut = asaPoolTick.zfill(12)

KeyError: 'unit-name'

**Comment by HashingSlash** [comment]
Hi, I believe I have this issue resolved now. Please let me know if it's still happening for you.
